name: Trigger auto deployment for pythondjango-containerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/pythondjango-containerapp-AutoDeployTrigger-386a7e7d-2b71-49db-8936-d9622a770447.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PYTHONDJANGOCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: acrpythondjango.azurecr.io
          registryUsername: ${{ secrets.PYTHONDJANGOCONTAINERAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PYTHONDJANGOCONTAINERAPP_REGISTRY_PASSWORD }}
          containerAppName: pythondjango-containerapp
          resourceGroup: capppythondjango
          imageToBuild: acrpythondjango.azurecr.io/pythondjango-containerapp:${{ github.sha }}
          
            

     

